### ISSUE TITLE
Name of the repo

### ISSUE THREAD

**Issue by rosiakpiotr** [TMALFSSISAWBOJBUMA/gra#2]
Could you perhaps come up with some better name for the repository? `gra` seems very dull and ruins aesthetics of your profile.

**Comment by rosiakpiotr** [comment]
@TMALFSSISAWBOJBUMA is this repo abandoned? You haven't replied since 4 minutes. Its outrageous.

**Comment by pieszke** [comment]
Thanks for bringing this to my attention. This repo is abandoned indeed and is left as a part of my journey in software development. I'll archive it to avoid further issues :)
